"use client";

import { useEffect, useState } from "react";

type Detail = {
  patient_name: string; dni: string; date_label: string; time: string; study_type: string; coverage_type: string;
  result_code: string; result_label: string; medical_control_today: boolean; technician_notes: string; bronchodilator_positive: boolean;
  file: { present: boolean; url: string; name: string; is_image: boolean; status: { label: string; detail: string; key: string } };
  suggestion: { code?: string; reason?: string; values?: Record<string, string | number> };
  vitals: { rest: { so2: number | null; fc: number | null; so2_tone: string }; post: { so2: number | null; fc: number | null; so2_tone: string }; walk: { label: string; tone: string; borg_final: number | null } };
  legacy_review_url: string; previous: { id: number; name: string } | null; next: { id: number; name: string } | null; pending_total: number;
};

export default function ReviewDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState("");
  useEffect(() => { void params.then((value) => setId(value.id)); }, [params]);
  useEffect(() => { if (!id) return; let active = true; void fetch(`/api/v1/revision-medica/${id}/`, { cache: "no-store", credentials: "same-origin" }).then(async (response) => { if (!response.ok) throw new Error(response.status === 403 ? "Esta sesion no puede abrir la ficha medica." : "No se pudo cargar la ficha."); return response.json() as Promise<Detail>; }).then((payload) => { if (active) { setData(payload); setError(""); } }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Error de conexion."); }); return () => { active = false; }; }, [id]);
  return <main className="agenda-shell review-detail-next">{error && <p className="notice error">{error}</p>}{!data && !error && <p className="notice">Cargando ficha medica...</p>}{data && <><header className="review-detail-head"><div><a className="back-link" href="/revision-medica/">Volver a Revision medica</a><h1>{data.patient_name}</h1><p>{data.date_label} | {data.time} | {data.study_type} | {data.coverage_type} | DNI {data.dni}</p></div><a className="legacy-review-button" href={`/django${data.legacy_review_url}`}>Abrir formulario medico</a></header>{data.medical_control_today && <p className="medical-control-banner">Control medico hoy</p>}<section className="review-detail-navigation"><span>{data.pending_total} pendiente{data.pending_total === 1 ? "" : "s"} para diagnostico</span><div>{data.previous && <a href={`/revision-medica/${data.previous.id}/`}>Anterior: {data.previous.name}</a>}{data.next && <a href={`/revision-medica/${data.next.id}/`}>Siguiente: {data.next.name}</a>}</div></section><section className="review-detail-grid"><article className="review-document"><div className="document-status"><b>{data.file.status.label}</b><span>{data.file.status.detail}</span></div>{data.file.present ? data.file.is_image ? <img src={`/django${data.file.url}`} alt={`Estudio de ${data.patient_name}`} /> : <iframe src={`/django${data.file.url}#view=FitH`} title={`Estudio de ${data.patient_name}`} /> : <p className="empty">No hay PDF o foto cargada para este paciente.</p>}</article><aside className="review-clinical"><section><h2>Signos y caminata</h2><div className="vitals-next"><Vital label="SO2 reposo" value={data.vitals.rest.so2} tone={data.vitals.rest.so2_tone} /><Vital label="FC reposo" value={data.vitals.rest.fc} /><Vital label="SO2 post" value={data.vitals.post.so2} tone={data.vitals.post.so2_tone} /><Vital label="FC post" value={data.vitals.post.fc} /></div><p className={`walk-next ${data.vitals.walk.tone}`}>{data.vitals.walk.label}{data.vitals.walk.borg_final != null ? ` | Borg final ${data.vitals.walk.borg_final}` : ""}</p></section>{data.suggestion.code && <section className="suggestion-next"><h2>Sugerido por el PDF</h2><b>{data.suggestion.code}</b><p>{data.suggestion.reason || "Valores detectados para orientar la revision."}</p></section>}<section className={`result-next ${data.result_code ? "saved" : ""}`}><h2>Resultado final</h2><b>{data.result_code || "Pendiente de medico"}</b><p>{data.result_label || "Abrir el formulario medico para guardar el resultado final."}</p>{data.bronchodilator_positive && <span>Broncodilatador positivo</span>}</section>{data.technician_notes && <section className="notes-next"><h2>Nota para el medico</h2><p>{data.technician_notes}</p></section>}</aside></section></>}</main>;
}
function Vital({ label, value, tone = "" }: { label: string; value: number | null; tone?: string }) { return <div className={`vital-next ${tone}`}><span>{label}</span><b>{value ?? "-"}</b></div>; }
