# Generated by Django 6.0.5 on 2026-06-01 01:41

import clinic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150, verbose_name="Apellido y nombre")),
                ("dni", models.CharField(max_length=20, unique=True, verbose_name="DNI")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Fecha de nacimiento")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Telefono")),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ReferringPhysician",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150, unique=True, verbose_name="Nombre")),
                ("is_default", models.BooleanField(default=False, verbose_name="Por defecto")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Medico derivante",
                "verbose_name_plural": "Medicos derivantes",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encounter_date", models.DateField(verbose_name="Fecha de atencion")),
                ("encounter_time", models.TimeField(blank=True, null=True, verbose_name="Hora de atencion")),
                (
                    "study_type",
                    models.CharField(
                        choices=[("Ciclometria", "Ciclometria"), ("Espirometria", "Espirometria")],
                        default="Ciclometria",
                        max_length=30,
                        verbose_name="Tipo de estudio",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Cargada", "Cargada"),
                            ("Revisada por medico", "Revisada por medico"),
                            ("Informe generado", "Informe generado"),
                            ("Entregada", "Entregada"),
                        ],
                        default="Cargada",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[("Mutual", "Mutual"), ("Particular", "Particular")],
                        default="Particular",
                        max_length=20,
                        verbose_name="Cobertura",
                    ),
                ),
                ("coverage_name", models.CharField(blank=True, max_length=120, verbose_name="Nombre mutual")),
                ("affiliate_number", models.CharField(blank=True, max_length=80, verbose_name="Numero afiliado")),
                ("validated_at", models.DateTimeField(blank=True, null=True, verbose_name="Validado el")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="encounters", to="clinic.patient"),
                ),
                (
                    "referring_physician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="clinic.referringphysician",
                        verbose_name="Medico derivante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atencion",
                "verbose_name_plural": "Atenciones",
                "ordering": ["-encounter_date", "-encounter_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("pdf_resultado", "PDF resultado"),
                            ("foto_resultado", "Foto resultado"),
                            ("informe_docx", "Informe DOCX"),
                            ("informe_pdf", "Informe PDF"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de archivo",
                    ),
                ),
                ("original_name", models.CharField(max_length=255, verbose_name="Nombre original")),
                ("file", models.FileField(upload_to=clinic.models.attachment_upload_to, verbose_name="Archivo")),
                ("mime_type", models.CharField(blank=True, max_length=120, verbose_name="Mime type")),
                (
                    "uploaded_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "encounter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="clinic.encounter"),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("Espirometria", "Espirometria"), ("Completo", "Completo"), ("Mutual", "Mutual")],
                        max_length=30,
                        verbose_name="Tipo de informe",
                    ),
                ),
                ("generator_version", models.CharField(blank=True, max_length=50, verbose_name="Version del generador")),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="clinic.attachment",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generated_reports", to="clinic.encounter"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Informe generado",
                "verbose_name_plural": "Informes generados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpirometryResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "respiratory_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Normal", "Normal"),
                            ("Obstructivo", "Obstructivo"),
                            ("Restrictivo", "Restrictivo"),
                            ("Mixto", "Mixto"),
                        ],
                        max_length=20,
                        verbose_name="Patron respiratorio",
                    ),
                ),
                (
                    "obstruction_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Leve", "Leve"),
                            ("Moderada", "Moderada"),
                            ("Moderadamente severa", "Moderadamente severa"),
                            ("Severa", "Severa"),
                        ],
                        max_length=30,
                        verbose_name="Grado de obstruccion",
                    ),
                ),
                (
                    "restriction_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Leve", "Leve"),
                            ("Moderada", "Moderada"),
                            ("Moderadamente severa", "Moderadamente severa"),
                            ("Severa", "Severa"),
                        ],
                        max_length=30,
                        verbose_name="Grado de restriccion",
                    ),
                ),
                ("bronchodilator_positive", models.BooleanField(default=False, verbose_name="Broncodilatador positivo")),
                ("physician_comment", models.TextField(blank=True, verbose_name="Comentario medico")),
                (
                    "encounter",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="spirometry_result", to="clinic.encounter"),
                ),
            ],
            options={
                "verbose_name": "Resultado espirometrico",
                "verbose_name_plural": "Resultados espirometricos",
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("so2_rest", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SO2 en reposo")),
                ("fc_rest", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="FC en reposo")),
                ("ta_rest", models.CharField(blank=True, max_length=30, verbose_name="TA en reposo")),
                ("so2_post", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SO2 post prueba")),
                ("fc_post", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="FC post prueba")),
                (
                    "encounter",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="vital_signs", to="clinic.encounter"),
                ),
            ],
            options={
                "verbose_name": "Signos vitales",
                "verbose_name_plural": "Signos vitales",
            },
        ),
        migrations.CreateModel(
            name="WalkTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distance_meters",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(100, "100"), (200, "200")], null=True, verbose_name="Distancia"
                    ),
                ),
                ("completed", models.BooleanField(default=False, verbose_name="Prueba concluida")),
                ("stopped", models.BooleanField(default=False, verbose_name="Se detuvo")),
                ("symptoms", models.BooleanField(default=False, verbose_name="Presento sintomas")),
                ("borg_final", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Borg final")),
                (
                    "encounter",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="walk_test", to="clinic.encounter"),
                ),
            ],
            options={
                "verbose_name": "Prueba de caminata",
                "verbose_name_plural": "Pruebas de caminata",
            },
        ),
    ]
