# Generated by Django 6.0.5 on 2026-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_encounter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atendido el'),
        ),
    ]
